version: '2'
services:
  api:  
    image: api
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"

  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
