version: '2'
services:
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - api1
      - api2
    ports:
      - '80:8080'
      - '81:1936'
    depends_on:
      - api1
      - api2
    environment:
      - ADDITIONAL_SERVICES=sparrow:api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api1:  
    image: sparrow_api
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
      
  api2:  
    image: sparrow_api
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
